system:
  title: 'デザイン管理システム'
  url: 'https://design-dms.herokuapp.com/'
  twitter:
    url: 'https://twitter.com/'
    tweet_url: 'http://twitter.com/intent/tweet?'
    share_url: 'http://twitter.com/share?'
  portal:
    limit: 10
