system:
  title: 'デザイン管理システム'
  url: 'https://design-dms.herokuapp.com/'
  description: 'あなたの作った型紙を共有して、服飾の輪を広げよう！自分だけでのナレッジとして持っているのも良いですが、みんなで共有して、楽しい服飾ライフを過ごしませんか？！'
  twitter_site: newburu
  twitter:
    url: 'https://twitter.com/'
    tweet_url: 'http://twitter.com/intent/tweet?'
    share_url: 'http://twitter.com/share?'
  portal:
    limit: 10
